language: php
php:
    - 7.2
install:
    - composer global require 'hirak/prestissimo:^0.3' --no-suggest --no-interaction --prefer-dist --no-progress
    - composer install --no-suggest --no-interaction --no-scripts
script:
    - vendor/bin/phpunit
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyse src tests --level=5 --no-progress
directories:
    - $HOME/.composer/cache/files
