name: Tests
on: push

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.4', '8.0']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup PHP ${{ matrix.php-versions }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: prestissimo
                  coverage: none
              env:
                  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
            - run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install Dependencies with --prefer-${{ matrix.composer-deps }}
              run: composer update --prefer-stable --no-suggest --no-interaction --no-progress

            - name: Run PHPUnit
              run: vendor/bin/phpunit

            - name: Run PHP Code Sniffer
              run: vendor/bin/phpcs

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --no-progress
