on:
    pull_request:
        branches:
            - master

jobs:
    test:
        container: prooph/composer:7.2
        volumes:
            - .:/
        steps:
            - name: Install composer
              run: composer install -n
